# Generated by Django 4.1.5 on 2023-01-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
