# Generated by Django 4.1.5 on 2023-01-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_idea_like_users_idea_user_delete_ideastar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='user',
        ),
        migrations.CreateModel(
            name='IdeaStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.idea')),
            ],
        ),
    ]
