# Generated by Django 4.1.5 on 2023-01-18 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_remove_idea_like_users_remove_idea_user_ideastar'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='like_users',
            field=models.ManyToManyField(null=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='IdeaStar',
        ),
    ]
