# Generated by Django 4.1.5 on 2023-01-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_delete_like_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pressed',
            field=models.BooleanField(default=False),
        ),
    ]
