# Generated by Django 4.1.5 on 2023-01-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('AC', '액션'), ('CR', '범죄'), ('SF', 'SF'), ('CO', '코미디'), ('RC', '로맨스 코미디'), ('RO', '로맨스'), ('ME', '멜로'), ('TH', '스릴러'), ('HO', '공포'), ('WA', '전쟁'), ('SP', '스포츠'), ('FA', '판타지'), ('MU', '음악')], max_length=2),
        ),
    ]
